config/routes.rb
GoApp::Application.routes.draw do

  root to: "games#index"

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  resources :sessions

  get "sign_up" => "users#new", :as => "sign_up"
  resources :users, :only => [:new, :create, :show]

  resources :games do
    member do
      post :join
      post :new_move
      post :pass_turn
      post :undo_turn
      post :request_undo
      post :mark_stones
      post :done_scoring
      post :resign
    end
  end

  # catch all for non-existent URLs
  # haven't decided which of these two ways is better, but leaning towards 2nd way (not commented out)
  #get ":url" => "application#redirect_bad_urls", :constraints => { :url => /.*/ }
  get ":url" => "games#index", :constraints => { :url => /.*/ }
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :require_login, :except => :index
  before_action :find_game, except: [:index, :new, :create]
  before_action :generate_connection_id, only: [:index, :show]
  helper_method :current_player

  def index
    @open_games = Game.open.order('created_at DESC')
  end

  def new
    @game = Game.new
  end

  def create
    # todo: move defaults somewhere more logical
    @game = Game.new(
      description: params[:game][:description],
      creator: current_user,
      board_size: params[:game][:board_size],
      status: Game::OPEN,
      mode: Game::NOT_RANKED,
      time_settings: "none"
    )

    if @game.save
      send_realtime_data(room_id: "lobby", event_name: "new-open-game",
        payload: { open_game_html: render_to_string(partial: 'open_game', locals: { game: @game, show_link: true }) }
      )
      redirect_to games_path, notice: 'Game was created successfully!'
    else
      render "new"
    end
  end

  def join
    if @game.open? && current_user != @game.creator
      @game.pregame_setup(current_user)

      send_realtime_data(event_name: "challenger-joined-game-#{@game.id}", room_id: "lobby",
        payload: { challenger_username: current_user.username, show_game_url: game_path(@game) })
      send_realtime_data(event_name: "remove-open-game", room_id: "lobby", payload: { game_id: @game.id })

      respond_to { |format| format.json }
    else
      render nothing: true
    end
  end

  def show
    if @game.end_game_scoring?
      @just_entered_scoring_phase = true

      tiles_to_render = @game.tiles_to_render_during_scoring(overwrite_data_store=true)
      @tiles = decorated_tiles(current_player, tiles_to_render)
      @json_scoring_data = json_scoring_updates(reset_content_type_to_html=true)
    end
    @tiles = decorated_tiles(current_player, @game.tiles_to_render(current_player))
  end

  def new_move
    update_helper(@game.new_move(params[:new_move].to_i, current_player))
  end

  def pass_turn
    if @game.pass(current_player)
      if @game.active?
        update_helper(true)
      elsif @game.end_game_scoring?
        @just_entered_scoring_phase = true
        scoring_helper(true)
      end
    else
      render nothing: true
    end
  end

  def undo_turn
    valid_undo_approval = (params[:undo_status] == "approved" && decrypt(params[:move_num]) == @game.move_num)
    undo_requester = current_player.opponent
    update_helper(valid_undo_approval && @game.undo(undo_requester))
  end

  def request_undo
    if @game.active? && @game.has_user?(current_user)
      # the move_num value encrypted here is verified in games#undo_turn if the undo request is approved
      approval_form = render_to_string(partial: 'undo_approval_form', locals: { move_num: encrypt(@game.move_num) })
      send_realtime_data(event_name: "undo-request", payload: { approval_form: approval_form })
    end
    render nothing: true
  end

  def mark_stones
    scoring_helper(@game.mark_stone(params[:stone_pos].to_i, params[:mark_as]))
  end

  def done_scoring
    if @game.update_done_scoring_flags(current_user)
      if @game.finished?
        # would be nice to not have to parse this (look into RABL, which allows skipping the hash to json string step)
        data = JSON.parse(render_to_string(template: 'games/finalize_game', formats: [:json]))
        send_realtime_data(event_name: "game-finished", payload: data)
      end

      respond_to { |format| format.json { render 'games/finalize_game' } }
    else
      render nothing: true
    end
  end

  def resign
    if @game.resign(current_player)
      data = JSON.parse(render_to_string(template: 'games/finalize_game', formats: [:json]))
      send_realtime_data(event_name: "game-finished", payload: data)
      respond_to { |format| format.json { render 'games/finalize_game' } }
    else
      render nothing: true
    end
  end

  private

  def update_helper(update_action_was_successful)
    pretty_log_game_info("-- games#update_helper -- ")

    if update_action_was_successful
      @tiles = decorated_tiles(current_player, @game.tiles_to_render(current_player, updates_only=true))

      opponent = current_player.opponent
      opponent_data = JSON.parse(render_to_string(template: 'games/update', formats: [:json], locals: {
        tiles: decorated_tiles(opponent, @game.tiles_to_render(opponent, updates_only=true)),
        player: opponent
      }))

      logger.info "-- games#update_helper -- opponent_data: #{opponent_data.inspect}"
      send_realtime_data(event_name: "game-update", payload: opponent_data)

      respond_to do |format|
        format.json { render 'games/update', locals: { tiles: @tiles, player: current_player } }
      end
    else
      render nothing: true
    end
  end

  def scoring_helper(scoring_update_was_successful)
    if scoring_update_was_successful
      overwrite_data_store = (true if @just_entered_scoring_phase) || false
      @tiles = decorated_tiles(current_player, @game.tiles_to_render_during_scoring(overwrite_data_store))

      send_realtime_data(event_name: "scoring-update", payload: JSON.parse(json_scoring_updates))
      respond_to { |format| format.json { render 'games/scoring' } }
    else
      render nothing: true
    end
  end

  def json_scoring_updates(reset_content_type_to_html=false)
    json = render_to_string(template: 'games/scoring', formats: [:json])
    response.headers["Content-Type"] = 'text/html' if reset_content_type_to_html
    json
  end


  def decorated_tiles(player, tiles_to_render)
    last_pos = @game.active_board.pos

    scoring_display_mode = @game.end_game_scoring? || @game.finished?
    ko_pos = @game.get_ko_position(player) unless scoring_display_mode
    invalid_moves = @game.invalid_moves unless scoring_display_mode

    tiles_to_render.map do |pos, tile_state|
      new_tile = TilePresenter.new(
        board_size: @game.board_size,
        state: tile_state,
        pos: pos,
        user: player,
        game_status: @game.status,
        invalid_moves: invalid_moves
      )

      new_tile.territory_status = @game.territory_status(pos) if scoring_display_mode
      new_tile.is_dead_stone = true if scoring_display_mode && @game.has_dead_stone?(pos)

      new_tile.is_most_recent_move = true if pos == last_pos
      new_tile.is_ko = true if pos == ko_pos
      new_tile
    end
  end


  def send_realtime_data(event_data)
    event_data[:room_id] = @room_id unless event_data.key?(:room_id)
    event_data[:connection_id_to_skip] = params[:connection_id]
    logger.info "-- games#send_realtime_data -- event_data: #{event_data.inspect}"
    $redis.publish "game-events", JSON.dump(event_data)
  end

  def find_game
    begin
      @game = Game.find(params[:id])
      @room_id = "game-#{@game.id}"
      pretty_log_game_info('----')
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The requested page does not exist."
      redirect_to games_path
    end
  end

  def current_player
    @current_player ||= @game.current_player(current_user)
  end

  def generate_connection_id
    @connection_id = generate_token
  end

  def pretty_log_game_info(prefix='')
    inspect_prefix = @game.inspect.split[0]
    log_msg1 = "game: #{inspect_prefix} object_id: #{@game.object_id},#{@game.inspect[(inspect_prefix.length)..-1]}"
    log_msg2 = "game.active_board: #{@game.active_board.inspect}"
    logger.info "#{prefix} #{log_msg1}"
    logger.info "#{prefix} #{log_msg2}"
  end

end

app/helpers/games_helper.rb
module GamesHelper

  RENDERER = ActionController::Base.new()

  def board_size_options
    options_for_select(
      (GoApp::MIN_BOARD_SIZE..GoApp::BOARD_SIZE).to_a,
      [GoApp::BOARD_SIZE]
    )
  end

  def status_message(game)
    board = game.active_board

    msg = ""
    if game.move_num == 0
      msg << "Game Start"

    elsif game.finished?
      msg << "Game Over: #{final_result_message_short(game)}"

    else
      msg << "Move #{game.move_num}"
      msg << " (#{game.inactive_player.color.capitalize[0]}"
      if board.pos
        col_num = board.pos % game.board_size
        row_label = game.board_size - (board.pos / game.board_size)
        msg << " #{GoApp::COLUMN_LABELS[col_num]}#{row_label})"
      elsif board.pass
        msg << " pass)"
      else
        logger.info "-- GamesHelper.status_message -- oops, something wrong"
      end
    end

    msg << ": #{game.active_player.color.capitalize} to play" unless game.finished?
    msg
  end

  def scoring_instructions
    content_str = [
      "The game has entered the scoring phase.",
      "Please identify which stone groups are dead by clicking on them.",
      "You can mark a stone group as not dead by clicking on it while holding the <code>SHIFT</code> key.",
      "When finished, press the 'Done' button."
    ].join(" ")
    RENDERER.render_to_string(partial: 'games/notification', locals: { lines_of_content: [content_str] })
  end

  def game_finished_message(game)
    lines_of_content = [
      "The game is over.",
      (score_details_message(game, game.white_player) if game.win_by_score?),
      (score_details_message(game, game.black_player) if game.win_by_score?),
      "Final result: #{final_result_message(game)}"
    ].compact

    Rails.logger.info "--- GamesHelper.game_finished_message -- lines_of_content: #{lines_of_content.inspect}"
    RENDERER.render_to_string(partial: 'games/notification', locals: { lines_of_content: lines_of_content })
  end

  def score_details_message(game, player)
    details_message = "Score for #{player.color}: "
    details_message << game.point_details(player).map { |type, points| "#{prettify(points)} #{type}" }.join(" + ")
    details_message << " = #{prettify(player.point_count)}"
  end

  def final_result_message(game)
    msg = ""
    if game.tie?
      msg << "tie game."
    else
      winner_name = "#{game.winner.username} (#{game.winner.color})"
      loser_name = "#{game.winner.opponent.username} (#{game.winner.opponent.color})"

      if game.win_by_resign?
        msg << "#{loser_name} has resigned. #{winner_name} has won."
      elsif game.win_by_time?
        msg << "#{loser_name} ran out of time. #{winner_name} has won."
      else
        msg << "#{winner_name} has won by #{prettify(game.point_difference)} points."
      end
    end

    msg
  end

  def final_result_message_short(game)
    msg = ""
    if game.tie?
      msg << "Tie"
    elsif game.finished?
      msg << "#{game.winner.color.capitalize[0]}+"
      msg << (("R" if game.win_by_resign?) || ("time" if game.win_by_time?) || "#{prettify(game.point_difference)}")
    end
    msg
  end

  def prettify(float)
    (float.to_i if float.to_i == float) || float
  end

end

app/views/games/_game_stats.html.erb
<h1 class='header-text'>
  <%= game.white_player.username %> (white) vs. <%= game.black_player.username %> (black)
</h1>

<div class='game-status-info'>
  <p>
    <span id='status-message'><%= status_message(game) %></span><br>

    Captures -- Black: <span id='black-capture-count'><%= game.black_capture_count %></span>
    White: <span id='white-capture-count'><%= game.white_capture_count %></span>

    <% div_params = [[:id, 'score-container'], ([:class, 'hidden'] unless game.show_score?)] %>
    <%= content_tag :div, Hash[div_params.compact] do %>
      Score -- Black: <span id='black-point-count'><%= game.black_point_count %></span>
      White: <span id='white-point-count'><%= game.white_point_count %></span>
    <% end %>
  </p>
</div>

app/views/games/_join_game_form.html.erb
<div id='join-game-form'>
  <div class='modal-message'>
    Join game created by <span id='challenged-player' class='notice-highlight'></span>?
  </div>

  <div class='centered-buttons'>
    <%= button_tag "Ok", { type: 'button', class: 'ok-button' } %>
    <%= button_tag "Cancel", { type: 'button', class: 'cancel-button' } %>
  </div>
</div>

app/views/games/_notification.html.erb
<div id='notification-container'>
  <div class='modal-message'>
    <% lines_of_content.each_with_index do |content_line, index| %>
      <% if index > 0 %><br><% end %>
      <%= content_line.html_safe %>
    <% end %>
  </div>

  <%= button_tag "Ok", { type: 'button', class: 'ok-button' } %>
</div>

app/views/games/_open_game.html.erb
<tr id='game-<%= game.id %>' class='open_game'>
  <td><%= game.creator.username %></td>
  <td class='centered'><%= game.board_size %> x <%= game.board_size %></td>
  <td><%= game.description %></td>
  <td class='centered'>
    <% show_link = local_assigns.fetch(:show_link, false) %>
    <% if game.creator != current_user || show_link %>
      <%= link_to "Join", join_game_path(game), class: 'join-game-link', "data-username" => game.creator.username %>
    <% else %>
      -
    <% end %>
  </td>
</tr>

app/views/games/_resign_confirmation_dialog.html.erb
<div class='modal-message'>
  Are you sure you want to resign? Your opponent will be declared the winner.
</div>

<div class='centered-buttons'>
  <%= button_tag "Yes", { type: 'button', class: 'yes-button' } %>
  <%= button_tag "Cancel", { type: 'button', class: 'cancel-button' } %>
</div>

app/views/games/_tile.html.erb
<% if tile.on_left_side? %>
  <tr>
<% end %>

<td>
  <%= content_tag :div, id: "tile-#{tile.pos}", :class => tile.container_classes, "data-pos" => tile.pos do %>
    <%= image_tag(tile.display_image_path, { alt: tile.alt_text, class: "tile-image" }) %>
    <% if tile.has_preview_stone? %>
      <%= image_tag(tile.preview_stone_path, { alt: "preview stone", class: "hover-image" }) %>
    <% end %>
  <% end %>
</td>

<% if tile.on_right_side? %>
  </tr>
<% end %>

app/views/games/_undo_approval_form.html.erb
<div id='undo-approval-container'>
  <div class='modal-message'>
    Your opponenet
    <span class='notice-highlight'><%= current_user.username %></span>
    has requested an undo for their most recent move.<br>
    Do you want to allow the undo?
  </div>

  <%= form_tag({ action: :undo_turn }, { id: 'undo-approval-form' }) do %>
    <%= submit_tag 'Yes', name: 'approved', id: 'yes-button', class: 'button' %>
    <%= submit_tag 'No', name: 'rejected', id: 'no-button', class: 'button' %>
    <%= hidden_field_tag :move_num, move_num %>
  <% end %>
</div>

app/views/games/index.html.erb
<h1>Open Games</h1>
<h3>Find a game to join!</h3>

<table id='open-games-table' class='game-list'>
  <thead>
    <tr>
      <th class='username-col'>User</th>
      <th class='board-size-col centered'>Size</th>
      <th class='index-description-col'>Description</th>
      <th class='first-link-col centered'>Join</th>
    </tr>
  </thead>

  <% @open_games.each do |game| %>
    <%= render 'open_game', { game: game } %>
  <% end %>
</table>

<p><%= link_to "Create new game", new_game_path %></p>

<div id="join-game-content-wrapper" class='hidden'>
  <div class='join-game-content'>
    <%= render 'join_game_form' %>
  </div>
</div>

<%= javascript_tag do %>
  window.connection_id = '<%= @connection_id %>';
  <% if current_user && current_user.has_open_games? %>
    window.open_game_ids = <%= current_user.open_game_ids.to_json.html_safe %>;
  <% end %>
<% end %>

<% javascript 'index.js' %>

app/views/games/new.html.erb
<%= render "layouts/back_to_games_list" %>

<h1>New Game</h1>

<%= render 'layouts/form_errors', :form_obj => @game if @game %>

<%= form_for @game, url: { :action => :create } do |f| %>
  <p>
    <%= f.label('description', 'Description:') %>
    <%= f.text_field('description') %>
  </p>
  <%= f.label('board_size', 'Size:') %>
  <%= f.select('board_size', board_size_options) %>
  <p><%= f.submit('Submit') %></p>
<% end %>

app/views/games/show.html.erb
<%= render "layouts/back_to_games_list" %>

<div id='game_container'>

  <div id='header-container'>
    <%= render 'game_stats', { game: @game } %>
  </div>

  <div id='table-container'>
    <div id='board_container' class='centered-tables'>
      <div id='game-actions-container'>
        <%= form_tag({ action: :pass_turn }, { id: 'pass-turn-form' }) do %>
          <%= submit_tag 'Pass', class: 'button', id: 'pass-button',
            disabled: current_player.not_their_turn? || @game.finished? %>
        <% end %>

        <%= form_tag({ action: :request_undo }, { id: 'request-undo-form', remote: true }) do %>
          <%= submit_tag 'Undo', class: 'button', id: 'undo-button',
            disabled: current_player.hasnt_played_a_move? || @game.finished? %>
          <%= hidden_field_tag 'connection_id', @connection_id %>
        <% end %>

        <%= form_tag({ action: :done_scoring }, { id: 'done-scoring-form' }) do %>
          <% css_classes = ["button", ("hidden" if !@game.end_game_scoring?)] %>
          <%= submit_tag 'Done', name: 'done', class: css_classes.compact.join(" "), id: "done-scoring-button",
            disabled: current_player.not_part_of_game? || @game.finished? %>
        <% end %>

        <%= form_tag({ action: :resign }, { id: 'resign-form' }) do %>
          <%= submit_tag 'Resign', name: 'resign', class: "button", id: "resign-button",
            disabled: current_player.not_part_of_game? || @game.finished? %>
        <% end %>
      </div>

      <%= form_tag({ action: :new_move }, { id: 'board-form' }) do %>
        <table id='board-table' class='board-table'>
          <%= render partial: 'games/tile', collection: @tiles %>
        </table>
      <% end %>
    </div>

    <div id='chat-container' class='centered-tables'>
      <div id='chat-header'><h1 class='header-text'>Game Chat</h1></div>

      <table id='chat-table'>
        <tr id='top-buffer-row'></tr>
        <tr id='bottom-buffer-row'></tr>
        <tr id='chat-input-row'>
          <td id='message-input-cell' colspan="3">
            <%= text_field_tag 'message', nil, class: 'message-input', id: 'message-input' %>
          </td>
          <td id='chat-button-cell'>
            <%= button_tag 'Send', id: 'send-message-button' %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

<div id="resign-confirmation-wrapper" class='hidden'>
  <div class='confirmation-content'>
    <%= render 'resign_confirmation_dialog' %>
  </div>
</div>

<%= javascript_tag do %>
  window.room_id = '<%= @room_id %>';
  window.connection_id = '<%= @connection_id %>';
  window.username = '<%= current_player.username %>';

  <% if @just_entered_scoring_phase %>
    $(document).ready(function() {
      update_scoring(<%= @json_scoring_data.html_safe %>);
    });
  <% end %>
<% end %>

<% javascript 'games.js' %>