config/routes.rb
GoApp::Application.routes.draw do

  root to: "games#index"

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  resources :sessions

  get "sign_up" => "users#new", :as => "sign_up"
  resources :users, :only => [:new, :create, :show]

  resources :games do
    member do
      post :join
      post :new_move
      post :pass_turn
      post :undo_turn
      post :request_undo
      post :mark_stones
      post :done_scoring
      post :resign
    end
  end

  # catch all for non-existent URLs
  # haven't decided which of these two ways is better, but leaning towards 2nd way (not commented out)
  #get ":url" => "application#redirect_bad_urls", :constraints => { :url => /.*/ }
  get ":url" => "games#index", :constraints => { :url => /.*/ }
end

app/views/layouts/_back_to_games_list.html.erb
<% content_for :extra_nav_links do %>
  <% link_to "Back to open games", games_path %>
<% end %>

app/views/layouts/_form_errors.html.erb
<% if form_obj.errors.any? %>
  <div class="error_messages">
    <ul>
      <% for message in form_obj.errors.full_messages %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="user_nav">
    <% if current_user %>
      Logged in as <%= current_user.username %>.
      <%= link_to "Log out", log_out_path %> or visit <%= link_to "your profile", current_user %>.
    <% else %>
      <%= link_to "Sign up", sign_up_path %> or <%= link_to "log in", log_in_path %>
    <% end %>
    <br>
    <%= yield(:extra_nav_links) %>
  </div>

  <% if flash[:notice].present? %>
    <p class='notice'><b>Notice:</b> <%= flash[:notice] %></p>
  <% end %>

  <% if flash[:alert].present? %>
    <p class='alert'><b>Alert:</b> <%= flash[:alert] %></p>
  <% end %>

  <%= yield %>

  <%= javascript_tag do %>
    window.sockjs_url = "<%= j ENV['NODEJS_URL'] %>";
  <% end %>

  <%= yield(:javascript_tags) %>
</body>
</html>